version: '3'

services:
  frontend:
    image: tonightbayastan/time_frontend_dev:1.0.0
    restart: always
    ports:
      - '3000:3000'
  api:
    image: tonightbayastan/time_backend_dev:1.1.1
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_db_pub:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  mysql_db_pub:
